version: '3'

services:

  prometheus:
    restart: always
    image: prom/prometheus:v2.11.1
    container_name: prometheus
    deploy:
      replicas: 1
    volumes:
      - prometheus-data:/prometheus
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./alertmanager/alert.rules/alerts.rules.yml:/alertmanager/alert.rules/alerts.rules.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=365d'
    network_mode: "host"

  node_exporter:
    restart: always
    image: prom/node-exporter:v0.18.1
    container_name: node_exporter
    deploy:
      replicas: 1
    network_mode: "host"

volumes:
  prometheus-data:
